name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lancer les tests
      - name: Run tests
        run: pytest

      # 5. Construire l’image Docker
      - name: Build Docker image
        run: docker build -t iris-app .

      # 6. (Optionnel) Simuler push de l’image
      - name: Simulate Docker push
        run: echo "docker push iris-app:latest"
